spring:
  application:
    name: front-service

server:
  port: 8888
  servlet:
    context-path: /front_service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    hostname: localhost